baseurl = "https://mangasf.github.io"
title = "Fran Mangas"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[languages]

    [languages.en]
        languagename = "EN"

        [languages.en.params]
            author = "Fran Mangas"
            info = "Software Engineering"
            poweredBy = "Powered by"

    [languages.es]
            languagename = "ES"

            [languages.es.params]
                author = "Fran Mangas"
                info = "Ingeniero Software"
                poweredBy = "Creado por"

[params]
    description = "Fran Mangas personal website"
    keywords = "developer"
    avatarurl = "images/avatar.jpeg"

    favicon_32 = "images/code-8x.png"
    favicon_16 = "images/code-8x.png"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]


[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/mangasf/"

[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/fran-mangas-a67070134/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/mangasf0/"


