baseurl = "https://mangasf.github.io"
title = "Fran Mangas"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[languages]

    [languages.en]
        languagename = "EN"

        [[languages.en.menu.main]]
            name = "Projects"
            weight = 1
            url = "#projects"

        [[languages.en.menu.main]]
            name = "Training"
            weight = 2
            url = "#training"

        [[languages.en.menu.main]]
            name = "Contact"
            weight = 3
            url = "#contact"

        [languages.en.params]
            author = "Fran Mangas"
            info = "Software Engineering"
            poweredBy = "Powered by"

            contactSectionName = "Contact"
            contactSectiondescription = "If you want to know about me or the projects I'm working on, you can write me, or maybe we can work together on some exciting project"
            formName = "Name"
            formEmail = "Email"
            formPhone = "Phone"
            formCompany = "Company"
            formMessage = "Message"
            formButton = "Send"

            projectsSectionName = "Projects"
            projectsSectiondescription = "In the last years, I have been working on different projects, here you can see some of them"

            trainingSectionName = "Training"
            trainingSectiondescription = "I also participate in some training projects, collaborating with Universities and Companies"
            collaboratorOneName = "Group4Layers Academy"
            collaboratorOneDescription1 = "Customized training for companies."
            collaboratorOneDescription2 = "Audit focused on analyzing the training needs of development teams."
            collaboratorOneDescription3 = "Creation of courses for individuals."
            collaboratorTwoName = "Ramon Llull University"
            collaboratorTwoDescription1 = "Collaboration in the teaching of the Master's Degree in High Performance Web Programming."
            collaboratorTwoDescription2 = "Collaboration in the teaching of the Master in Design and Development of Software Architectures."

    [languages.es]
        languagename = "ES"

        [[languages.es.menu.main]]
            name = "Proyectos"
            weight = 1
            url = "#projects"

        [[languages.es.menu.main]]
            name = "Formación"
            weight = 2
            url = "#training"

        [[languages.es.menu.main]]
            name = "Contacto"
            weight = 3
            url = "#contact"

        [languages.es.params]
            author = "Fran Mangas"
            info = "Ingeniero Software"
            poweredBy = "Creado por"

            contactSectionName = "Contacto"
            contactSectionDescription = "Si quieres saber más acerca de mi o sobre los proyectos en lo que estoy trabajando puedes escribirme, o quizás podamos trabajar juntos en algun proyecto emocionante"
            formName = "Nombre"
            formEmail = "Email"
            formPhone = "Teléfono"
            formCompany = "Empresa"
            formMessage = "Mensaje"
            formButton = "Enviar"

            projectsSectionName = "Proyectos"
            projectsSectiondescription = "En los últimos años he estado trabajando en diveros proyectos, aquí puedes ver algunos de ellos"

            trainingSectionName = "Formación"
            trainingSectiondescription = "También participo en algunos proyectos formativos, colaborando con Universidades y Empresas"
            collaboratorOneName = "Group4Layers Academy"
            collaboratorOneDescription1 = "Formación personalizada para empresas."
            collaboratorOneDescription2 = "Auditoría enfocada a analizar las necesidades formativas de equipos de desarrollo."
            collaboratorOneDescription3 = "Creación de cursos para particulares."
            collaboratorTwoName = "Universidad Ramon Llull"
            collaboratorTwoDescription1 = "Colaboración en la impartición del Master Universitario en Programación Web de Alto Rendimiento."
            collaboratorTwoDescription2 = "Colaboración en la impartición del Master en Diseño y Desarrollo de Arquitecturas Software."

[params]
    description = "Fran Mangas personal website"
    keywords = "developer"
    avatarurl = "images/avatar.jpeg"

    favicon_32 = "images/code-8x.png"
    favicon_16 = "images/code-8x.png"

    projects_images_dir="images/projects/"
    training_images_dir="images/training/"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]


[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/mangasf/"

[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/fran-mangas-a67070134/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/mangasf0/"


