baseurl = "https://mangasf.github.io"
title = "Fran Mangas"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[languages]

    [languages.en]
        languagename = "EN"

        [[languages.en.menu.main]]
            name = "Contact"
            weight = 1
            url = "#contact"

        [languages.en.params]
            author = "Fran Mangas"
            info = "Software Engineering"
            poweredBy = "Powered by"

            contactSectiondescription = "If you want to know about me or the projects I'm working on, you can write me, or maybe we can work together on some exciting project"
            formName = "Name"
            formEmail = "Email"
            formPhone = "Phone"
            formCompany = "Company"
            formMessage = "Message"
            formButton = "Send"

    [languages.es]
        languagename = "ES"

        [[languages.es.menu.main]]
            name = "Contacto"
            weight = 1
            url = "#contact"

        [languages.es.params]
            author = "Fran Mangas"
            info = "Ingeniero Software"
            poweredBy = "Creado por"

            contactSectionDescription = "Si quieres saber más acerca de mi o sobre los proyectos en lo que estoy trabajando puedes escribirme, o quizás podamos trabajar juntos en algun proyecto emocionante"
            formName = "Nombre"
            formEmail = "Email"
            formPhone = "Teléfono"
            formCompany = "Empresa"
            formMessage = "Mensaje"
            formButton = "Enviar"



[params]
    description = "Fran Mangas personal website"
    keywords = "developer"
    avatarurl = "images/avatar.jpeg"

    favicon_32 = "images/code-8x.png"
    favicon_16 = "images/code-8x.png"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]


[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/mangasf/"

[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/fran-mangas-a67070134/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/mangasf0/"


